# Use the official Ubuntu Bionic base image
FROM ubuntu:bionic

# Set environment variable to non-interactive mode for apt-get
ARG DEBIAN_FRONTEND=noninteractive

# Update the package lists and install necessary packages
RUN apt-get update && apt-get install -y -q \
    curl \
    gnupg \
    apt-transport-https \
    ca-certificates \
    apt-utils \
    build-essential \
    nodejs

# Add the Sawtooth repository and GPG key using an alternative key server (MIT)
RUN gpg --keyserver hkp://pgp.mit.edu:80 --recv-keys 8AA7AF1F1091A5FD \
    && gpg --export --armor 8AA7AF1F1091A5FD | apt-key add - \
    && echo 'deb [arch=amd64,signed-by=/usr/share/keyrings/sawtooth-archive-keyring.gpg] http://repo.sawtooth.me/ubuntu/chime/stable bionic universe' > /etc/apt/sources.list.d/sawtooth.list

# Update package lists again
RUN apt-get update

# Install Sawtooth related packages
RUN apt-get install -y -q python3-sawtooth-cli

# Install Node.js and npm
RUN curl -sL https://deb.nodesource.com/setup_12.x | bash - \
    && apt-get install -y -q nodejs

# Clean up package lists and cache
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

# Set the working directory for your application
WORKDIR /project/sawtooth-helloworld/helloworldClient

# Install Node.js dependencies and start your application
CMD npm install && npm start

# Expose the port on which your application listens
EXPOSE 3000
